"""completed d goal

Revision ID: 90cf5ad1fb53
Revises: b412d0ca85d1
Create Date: 2018-07-26 01:19:52.172149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90cf5ad1fb53'
down_revision = 'b412d0ca85d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'completed')
    # ### end Alembic commands ###
